# http://www.appveyor.com/docs/appveyor-yml

environment:
  # Visual Studio Version
  MSVS_VERSION: 2013

platform:
  - x64

build: off

install:
  - echo install
  - pwd

test_script:
  - echo test
  - pwd

artifacts:
  - path: 'packed/nightscout-ps1-*'
  - name: nightscout-ps1
  - type: file
