# http://www.appveyor.com/docs/appveyor-yml

environment:
  # Visual Studio Version
  MSVS_VERSION: 2013

platform:
  - x64

build:
  - echo build
  - pwd

install:
  - echo install
  - pwd

test_script:
  - echo test
  - pwd
