# http://www.appveyor.com/docs/appveyor-yml

environment:
  # Visual Studio Version
  MSVS_VERSION: 2013

platform:
  - x64

build: off

install:
  - git submodule sync
  - git submodule update --init
  - python --version
  - echo install
  - pwd

test_script:
  - echo test
  - pwd
