version: 2

jobs:

  build_linux:
    docker:
      - image: debian:jessie

    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run: ./build.sh

      - store_artifacts:
          path: packed

  build_macos:
    macos:
      xcode: "8.3.3"

    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run: ./build.sh

      - store_artifacts:
          path: packed

workflows:
  version: 2
  build_all:
    jobs:
      - build_linux
      - build_macos
