version: 2

jobs:

  build_alpine:
    docker:
      - image: alpine:3.5
    working_directory: /project

    steps:
      - run: apk add --no-cache build-base git python

      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run: pwd && ls
      - run: cat build.sh
      - run: sh /project/build.sh

      - store_artifacts:
          path: packed

  build_linux:
    docker:
      - image: debian:jessie
    working_directory: /project

    steps:
      - run: apt-get update && apt-get install -y build-essential git python

      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run: pwd && ls
      - run: ./build.sh

      - store_artifacts:
          path: packed

  build_macos:
    macos:
      xcode: "8.3.3"

    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run: ./build.sh

      - store_artifacts:
          path: packed

workflows:
  version: 2
  build_all:
    jobs:
      - build_alpine
      - build_linux
      - build_macos
